GET http://localhost:8082/currencies?min_value=1
###
GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/usd
###
GET http://localhost:8082/users
###
GET http://localhost:8082/users/6607d086-7159-4c26-beb1-280c9f9cbf3
###
GET http://localhost:8082/users/search?gender=male&age=49
###
GET http://localhost:8082/users/search?gender=-5
###
GET http://localhost:8082/users/search?age=-5
###
GET http://localhost:8082/users/search